version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: minijira
      MONGO_INITDB_ROOT_PASSWORD: minijira
      MONGO_INITDB_DATABASE: minijira
    ports:
      - 27016:27017
  server:
    build:
      context: server
    ports:
      - 5000:5000
    depends_on:
      - mongo
    volumes:
      - ./server:/usr/src/app
    environment:
      PORT: 5000
      MONGO_PATH: mongodb://minijira:minijira@mongo:27017/minijira?authSource=admin
      JWT_SECRET: kAzAkOvTrUeDeTeCtIVe
      AWS_REGION: eu-west-2
      AWS_POOL_ID: eu-west-2_nlPgYFjFU
      AWS_POOL_CLIENT_ID: r2flr3h1akor378ltbham857m
  client:
    build:
      context: client
    stdin_open: true
    ports:
      - 80:3000
    volumes:
      - ./client/src:/app/src
